#!/usr/bin/env python3
# Copyright (C) 2026 Johannes Lode (MTRONIG GmbH)
"""
gen_register_names_test.py — Generate P2 register name coverage test.

Tests that all P2 register names are accepted as inline asm operands in
both read (source) and write (destination) positions.

Usage:
    python3 gen_register_names_test.py > register-names.ll

The generated file is checked in to the repository. Regenerate when the
P2 register file changes (P2RegisterInfo.td).

Note: ina and inb are intentionally excluded — they are read-only hardware
registers and a MOV write would be semantically incorrect.
"""

import sys

def emit_header():
    print("; NOTE: Automatically generated by gen_register_names_test.py.")
    print("; To regenerate: python3 gen_register_names_test.py > register-names.ll")
    print("; RUN: llc -march=p2 < %s | FileCheck %s")
    print("; REQUIRES: p2-registered-target")
    print()
    print("; Tests that all P2 COG-RAM register names (c0-c463) and named")
    print("; special-purpose registers are accepted as inline asm operands")
    print("; in both source and destination positions.")
    print()

def emit_write(name):
    fname = name.replace(":", "_")
    print(f"define void @write_{fname}(i32 %val) {{")
    print(f"; CHECK-LABEL: write_{fname}:")
    print(f"; CHECK: mov {name}, {{{{r[0-9]+}}}}")
    print(f'    call void asm sideeffect "mov {name}, $0", "r"(i32 %val) nounwind')
    print(f"    ret void")
    print(f"}}")
    print()

def emit_read(name):
    fname = name.replace(":", "_")
    print(f"define i32 @read_{fname}() {{")
    print(f"; CHECK-LABEL: read_{fname}:")
    print(f"; CHECK: mov {{{{r[0-9]+}}}}, {name}")
    print(f'    %val = call i32 asm sideeffect "mov $0, {name}", "=r"() nounwind')
    print(f"    ret i32 %val")
    print(f"}}")
    print()

# COG-RAM registers c0-c463
cog_registers = [f"c{i}" for i in range(464)]

# Named special-purpose registers
# ina/inb excluded: read-only hardware registers, MOV write is semantically invalid
special_registers = [
    "r0",  "r1",  "r2",  "r3",  "r4",  "r5",  "r6",  "r7",
    "r8",  "r9",  "r10", "r11", "r12", "r13", "r14", "r15",
    "r16", "r17", "r18", "r19", "r20", "r21", "r22", "r23",
    "r24", "r25", "r26", "r27", "r28", "r29", "r30", "r31",
    "ijmp3", "iret3", "ijmp2", "iret2", "ijmp1", "iret1",
    "pa", "pb", "ptra", "ptrb",
    "dira", "dirb", "outa", "outb",
]

emit_header()

print("; -----------------------------------------------------------------------")
print("; COG-RAM registers c0-c463: write (destination) and read (source)")
print("; -----------------------------------------------------------------------")
print()
for name in cog_registers:
    emit_write(name)
    emit_read(name)

print("; -----------------------------------------------------------------------")
print("; Named special-purpose registers: write and read")
print("; -----------------------------------------------------------------------")
print()
for name in special_registers:
    emit_write(name)
    emit_read(name)
emit_read("ina")
emit_read("inb")
